---
title: "DataSci_exam"
author: "David Fjendbo"
date: "2023-05-20"
output: html_document
---
### setup ###
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load packages
library(pacman)
pacman::p_load(tidyverse, dplyr, ggplot2, ggpubr,car, scales)
```

```{r}
# set working directory
setwd("D:/Skole/CogSci/DataSci")
getwd()
```
```{r}
# load data
df <- read_csv("80k_dataset.csv", col_names = T)
df_quar <- read_csv("80k_quar_dataset.csv", col_names = T)
```
# Applications and calls #
### preprocess ###
```{r}
########################## preprocess ######################
# target rows
target <- c("Number of advising applications", "Number of advising calls")

# columns
df_calls <- df %>%
  select(matches("(...1|2017|2018|2019|2020|2021|2022)")) %>% 
  select(-"2011") %>% 
  rename("Type" =  "...1") %>% 
  filter(Type %in% target) %>% 
  select(-Type) %>% 
  t() %>% 
  as.data.frame()

colnames(df_calls) <- c("nb_apps", "nb_calls")

# making numeric
df_calls$nb_apps <- gsub(",", "", df_calls$nb_apps)
df_calls$nb_calls <- gsub(",", "", df_calls$nb_calls)
df_calls$nb_apps<- as.numeric(df_calls$nb_apps)
df_calls$nb_calls<- as.numeric(df_calls$nb_calls)

# making year column
df_calls$year <- rownames(df_calls)
df_calls$year<- as.numeric(df_calls$year)
rownames(df_calls) <- NULL

```

### plotting ###
```{r, fig.width=8, fig.height=4}
######################### plotting #######################
# set theme
theme_set(theme_minimal())

# plot for applications over time
p_apps <- ggplot(df_calls, aes(year, nb_apps)) +
  geom_point(shape = 21, fill = "steelblue", size = 3) +
  geom_smooth(method = "loess", se = FALSE, color = "darkorange", linetype = "dashed", linewidth = 1) +
  labs(x = "Year", y = "Number of Applications") +
  ggtitle("(A) Number of Applications Over Time") +
  theme(
    plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold"),
    legend.position = "top"
  )

# plot for calls over time
p_calls <- ggplot(df_calls, aes(year, nb_calls)) +
  geom_point(shape = 21, fill = "darkgreen", size = 3) +
  geom_smooth(method = "loess", color = "darkorange", linetype = "dashed", linewidth = 1) +
  labs(x = "Year", y = "Number of Calls") +
  ggtitle("Number of Calls Over Time") +
  theme(
    plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 12, face = "bold"),
    legend.position = "top"
  )

# showing the plots
ggarrange(p_apps, p_calls)
```

### analysis ###
```{r}
######################### analysis ########################
# t-test for number of calls vs actual calls
t.test(df_calls$nb_apps, df_calls$nb_calls, paired = T)
```

### quarterly dataset, applications vs calls ###
```{r, fig.width=8, fig.height=5}
########################## preprocess ##########################
# target rows
target <- c("Number of advising applications", "Number of advising calls")

# columns
df_calls_quar <- df_quar %>%
  select(matches("(Web and marketing|Q3 2017|Q4 2017|Q1 2018|Q2 2018|Q3 2018|Q4 2018|Q1 2019|Q2 2019|Q3 2019|Q4 2019|Q1 2020|Q2 2020|Q3 2020|Q4 2020|Q1 2021|Q2 2021|Q3 2021|Q4 2021|Q1 2022|Q2 2022|Q3 2022|Q4 2022)")) %>%  
  rename("Type" = "Web and marketing") %>% 
  filter(Type %in% target) %>% 
  select(-Type) %>% 
  t() %>% 
  as.data.frame()

# giving columns names
colnames(df_calls_quar) <- c("nb_apps", "nb_calls")

# making numeric
df_calls_quar$nb_apps<- as.numeric(df_calls_quar$nb_apps)
df_calls_quar$nb_calls<- as.numeric(df_calls_quar$nb_calls)

# making year column
df_calls_quar$year <- rownames(df_calls_quar)
rownames(df_calls_quar) <- NULL

############################ plotting  ##########################
# plot for number of applications over time
p_apps_quar <- ggplot(df_calls_quar, aes(year, nb_apps)) +
  geom_point(shape = 21, fill = "steelblue", size = 3) +
  geom_line(aes(group = 1), color = "darkorange", linetype = "dashed", linewidth = 1) +
  labs(x = "Year", y = "Number of Applications") +
  ggtitle("(B) Number of Applications Over Time") +
  scale_x_discrete(breaks = df_calls_quar$year[seq(1, length(df_calls_quar$year), 2)], limits = df_calls_quar$year) +
  theme(
    plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
    axis.text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 12, face = "bold"),
    legend.position = "top"
  )

# plot for number of calls over time
p_calls_quar <- ggplot(df_calls_quar, aes(year, nb_calls)) +
  geom_point(shape = 21, fill = "steelblue", size = 3) +
  geom_line(aes(group = 1), color = "darkorange", linetype = "dashed", linewidth = 1) +
  labs(x = "Year", y = "Number of Calls") +
  ggtitle("Number of Calls Over Time") +
  scale_x_discrete(breaks = df_calls_quar$year[seq(1, length(df_calls_quar$year), 2)], limits = df_calls_quar$year) +
  theme(
    plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
    axis.text = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title = element_text(size = 12, face = "bold"),
    legend.position = "top"
  )

# showing the plots
ggarrange(p_apps_quar, p_calls_quar)

##################### testing assumptions ########################
# summary statistics
summary(df_calls_quar)

# qq-plots for normality
qqnorm(df_calls_quar$nb_apps, main = "QQ Plot of Total FTE Web")
qqline(df_calls_quar$nb_apps, col = "darkorange")
qqnorm(df_calls_quar$nb_calls, main = "QQ Plot of visitors")
qqline(df_calls_quar$nb_calls, col = "darkorange")

# normality test
shapiro.test(df_calls_quar$nb_apps) # non-significantly different from Norm-dist
shapiro.test(df_calls_quar$nb_calls) # non-significantly different from Norm-dist


###################### analysis #########################
# performing t-test for calls vs applications
t.test(df_calls_quar$nb_apps, df_calls_quar$nb_calls, var.equal = F) # non-homoscedastic
wilcox.test(df_calls_quar$nb_apps, df_calls_quar$nb_calls) # non-linear
```



# Total FTE and Unique visitors #
#### using the quarterly dataset henceforth due to more datapoints ####
```{r, fig.width=7, fig.height=5}
###################### preprocess ##############################
# target rows
target <- c("Total core FTE web only", "Unique visitors")

# columns
df_uni <- df_quar %>%
  rename("Type" = "Web and marketing") %>% 
  filter(Type %in% target) %>% 
  select(-Type) %>% 
  t() %>% 
  as.data.frame()

# giving colnames
colnames(df_uni) <- c("total_fte_web", "visitors")

# making numeric
df_uni$visitors <- gsub(",", "", df_uni$visitors)
df_uni$visitors<- as.numeric(df_uni$visitors)
df_uni$total_fte_web<- as.numeric(df_uni$total_fte_web)

# making year column
df_uni$year <- rownames(df_uni)
rownames(df_uni) <- NULL

####################### plotting ######################
# plotting Total Core FTE and Number of Unique Visitors
ggplot(df_uni, aes(total_fte_web, visitors)) +
  geom_jitter(shape = 16, color = "darkblue", size = 3, alpha = 0.6) +
  geom_smooth(method = "lm", color = "darkorange", linetype = "dashed", size = 1) +
  labs(x = "Total FTE Web", y = "Visitors") +
  ggtitle("Relationship between Total FTE Web and Visitors") +
  scale_y_continuous(labels = comma) +
  theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"))

##################### testing assumptions ########################
# summary statistics
summary(df_uni)

# qq-plots for normality
qqnorm(df_uni$total_fte_web, main = "QQ Plot of Total FTE Web")
qqline(df_uni$total_fte_web, col = "darkorange")
qqnorm(df_uni$visitors, main = "QQ Plot of visitors")
qqline(df_uni$visitors, col = "darkorange")

# normality test
shapiro.test(df_uni$total_fte_web) # does not violate normality
shapiro.test(df_uni$visitors) # violates normality

# homoscedasticity 
model <- lm(visitors ~ total_fte_web, data = df_uni)

# risidual df
residuals_df <- data.frame(
  Predicted = fitted(model),
  Residuals = residuals(model)
)

# plotting risiduals vs predicted values
ggplot(residuals_df, aes(x = Predicted, y = Residuals)) +
  geom_point(shape = 16, color = "darkblue", size = 3, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "darkorange") +
  labs(x = "Predicted Values", y = "Residuals") +
  ggtitle("Residuals vs. Predicted Values") +
  theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"))

############################ analysis #######################
# performing pearson and spearman corr-test
cor.test(df_uni$total_fte_web, df_uni$visitors, method = "pearson")
cor.test(df_uni$total_fte_web, df_uni$visitors, method = "spearman")
```

# One-on-one FTE and AVG Usefulness #
```{r}
##################### preprocess ######################
# target rows
target <- c("Total core FTE direct only advising", "Total number of one-on-one calls")

# columns
df_one <- df_quar %>%
  select(-matches("(Q1 2016|Q2 2016|Q3 2016|Q4 2016|Q1 2017|Q2 2017|Q3 2017|Q4 2017)")) %>% 
  rename("Type" = "Web and marketing") %>% 
  filter(Type %in% target) %>% 
  select(-Type) %>% 
  t() %>% 
  as.data.frame()

# giving colnames
colnames(df_one) <- c("FTE_adv", "calls_one")

# making numeric
df_one$FTE_adv<- as.numeric(df_one$FTE_adv)
df_one$calls_one<- as.numeric(df_one$calls_one)

# making year column
df_one$year <- rownames(df_one)
rownames(df_one) <- NULL

#################### plotting ########################
# plotting FTE advising only and number of one-on-one calls
ggplot(df_one, aes(FTE_adv, calls_one)) +
  geom_jitter(shape = 16, color = "darkblue", size = 3, alpha = 0.6) +
  geom_smooth(method = "lm", color = "darkorange", linetype = "dashed", size = 1) +
  labs(x = "Total FTE Advising", y = "Number of One-on-one Calls") +
  ggtitle("Total FTE Advising vs. Number of One-on-one Calls") +
  theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"))

##################### testing assumptions ########################
# summary statistics
summary(df_uni)

# qq-plots for normality
qqnorm(df_one$FTE_adv, main = "QQ Plot of FTE_adv")
qqline(df_one$FTE_adv, col = "darkorange")
qqnorm(df_one$calls_one, main = "QQ Plot of calls_one")
qqline(df_one$calls_one, col = "darkorange")

# normality test
shapiro.test(df_one$FTE_adv) # does not violate normality
shapiro.test(df_one$calls_one) # violates normality

# homoscedasticity 
model <- lm(calls_one ~ FTE_adv, data = df_one)

# residual df
residuals_df <- data.frame(
  Predicted = fitted(model), 
  Residuals = residuals(model))

# plotting residuals vs predicted values
ggplot(residuals_df, aes(x = Predicted, y = Residuals)) +
  geom_point(shape = 16, color = "darkblue", size = 3, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "darkorange") +
  labs(x = "Predicted Values", y = "Residuals") +
  ggtitle("Residuals vs. Predicted Values") +
  theme_classic() +
  theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"))

############################ analysis #######################
# performing pearson and spearman corr-test
cor.test(df_one$FTE_adv, df_one$calls_one, method = "pearson")
cor.test(df_one$FTE_adv, df_one$calls_one, method = "spearman")

```

# financial costs and vacancy clicks #
### using the annual dataset since financial costs are not accessible for quarters ###
```{r, fig.width=8, fig.height=5}
### preprocess ###
# target rows
target <- c("Financial costs converted to USD, calendar year (estimate)", "Vacancy clicks")

# columns
df_fin <- df %>%
  select(matches("(...1|2018|2019|2020|2021|2022)")) %>%
  select(-"2011") %>% 
  rename("Type" = "...1") %>% 
  filter(Type %in% target) %>% 
  select(-Type) %>% 
  t() %>% 
  as.data.frame()

# giving colnames
colnames(df_fin) <- c("vac_clicks", "fin_cost")

# making numeric
df_fin$vac_clicks <- gsub(",", "", df_fin$vac_clicks)
df_fin$fin_cost <- gsub(",", "", df_fin$fin_cost)
df_fin$fin_cost <- gsub("\\$", "", df_fin$fin_cost)
df_fin$vac_clicks<- as.numeric(df_fin$vac_clicks)
df_fin$fin_cost<- as.numeric(df_fin$fin_cost)

# making year column
df_fin$year <- rownames(df_fin)
df_fin$year<- as.numeric(df_fin$year)
rownames(df_fin) <- NULL

######################## plotting ###########################
# plotting financial expenses and vacancy clicks
ggplot(df_fin, aes(fin_cost, vac_clicks)) +
  geom_jitter(shape = 21, fill = "darkblue", color = "white", size = 3, alpha = 0.7) +
  geom_smooth(method = "lm", color = "darkorange", linetype = "dashed", size = 1) +
  labs(x = "Financial Expenses", y = "Vacancy Clicks") +
  ggtitle("Relationship between Financial Expenses and Vacation Clicks") +
  scale_y_continuous(labels = scales::comma) +
  scale_x_continuous(labels = comma_format(scale = .000001, suffix = " mil")) +
  theme_minimal() +
  theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"),
        legend.position = "top")

##################### testing assumptions ########################
# summary statistics
summary(df_fin)

# qq-plots for normality
qqnorm(df_fin$fin_cost, main = "QQ Plot of fin_cost")
qqline(df_fin$fin_cost, col = "darkorange")
qqnorm(df_fin$vac_clicks, main = "QQ Plot of vac_clicks")
qqline(df_fin$vac_clicks, col = "darkorange")

# normality test
shapiro.test(df_fin$fin_cost) # violates normality
shapiro.test(df_fin$vac_clicks) # violates normality

# homoscedasticity
model <- lm(vac_clicks ~ fin_cost, data = df_fin)

# residuals df
residuals_df <- data.frame(
  Predicted = fitted(model), 
  Residuals = residuals(model))

# plotting residuals vs predicted values
ggplot(residuals_df, aes(x = Predicted, y = Residuals)) +
  geom_point(shape = 16, color = "darkblue", size = 3, alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "darkorange") +
  labs(x = "Predicted Values", y = "Residuals") +
  ggtitle("Residuals vs. Predicted Values") +
  theme_classic() +
  theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5),
        axis.text = element_text(size = 12),
        axis.title = element_text(size = 12, face = "bold"))

##################### analysis ########################
# performing pearson and spearman corr-test
cor.test(df_fin$fin_cost, df_fin$vac_clicks, method = "pearson")
cor.test(df_fin$fin_cost, df_fin$vac_clicks, method = "spearman")

```


